### PR TITLE
Make Blink compatible with object files built with `/bigobj`

### PR DESCRIPTION
**Pull request by Ybalrid**
See discussion in issue #23 

Do not merge yet : 

If things are going to get built with /bigobj too. The code that does the "linking and patching" needs a similar modification.

Probably around here : https://github.com/crosire/blink/blob/master/source/blink_linker.cpp#L136

### CODE REVIEW

**Comment by Ybalrid** [comment]
update : So, the changes mentioned in the first message are done, but there's still a crash occuring here: https://github.com/crosire/blink/blob/master/source/blink_linker.cpp#L375

(the section referenced by the symbol has a number way higher than the number of section in the object file - causing to be out of the range in side the vector)

I need to dig a bit more about what's going on right there.

**Comment by Ybalrid** [comment]
@crosire This thing is ready for you to checkout ;-)

**Comment by Ybalrid** [comment]
Fix #23

**Comment by crosire** [comment]
Thank you. Great job figuring this out! =)

I'm not a big fan of virtual functions/dynamic casting/exceptions though, so decided to implement this slightly differently with templates only. Hope you don't mind. Commit is below:

**Comment by Ybalrid** [comment]
@crosire I think I said it was a quick and dirty one, and I'm pretty happy that you used that as the basis for fixing what happens with "bigobj" coff files.
I'm going to check if everything works on my end with the commit in question :wink:

**Pull request closed without merging**
